version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    container_name: SpringBootLiquiBaseDemoDB
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sblb@123
      MYSQL_DATABASE: sblbDB
    restart: unless-stopped
